# Generated by Django 5.0.4 on 2024-05-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='pprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
